name: w_package
description: A W2O flutter package
version: 0.0.3
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_animate: ^4.1.1+1
  get_it: ^7.6.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter: